### ISSUE TITLE
Login with biometric device on Ubuntu

### ISSUE THREAD

**Issue by ximinchao** [ukui/biometric-authentication#3]
We've integrated our device into biometric-authentication service, and we could enroll / verify / delete finger print using "ukui-biometric-manager". Now we hope to login ubuntu with finger print, is there any help to do this ? Thank you~

**Comment by droiing** [comment]
1. Install these runtime dependencies:
`ukui-greeter ukui-screensaver libpam-biometric ukui-biometric-manager`

2. Open the ukui-biometric-manager, enroll at least one fingerprint and set you driver as default device (in driver page, "Default Device").

3. Return ukui-biometric-manager's DashBoard, set "Biometric Verification Status" open.

4. Reboot, and try login with your fingerprint.
